export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "BackEnd Developer",
    type: "Full Time",
    location: "Remote",
    companyName: "Google",
    companyURL: "Google.com",
    skills: ["JavaScript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "FrontEnd Developer",
    type: "Full Time",
    location: "Remote",
    companyName: "Google",
    companyURL: "Google.com",
    skills: ["JavaScript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "FrontEnd Developer",
    type: "Full Time",
    location: "Remote",
    companyName: "Google",
    companyURL: "Google.com",
    skills: ["JavaScript", "React.js", "Node.js"],
    link: "https://google.com/careers",
  },
];
